name: build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_NOLOGO: true
  ProjectLoadStyle: All
  

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  vs-2022-17-4:
    runs-on: windows-2022
    env:
      IMAGE: ghcr.io/visualon/builder:3.0.2@sha256:a327b6b9fb832e39860ee316b5326cad62f46c648705d7590996d1ff0f2f129a

    steps:
      - uses: actions/checkout@v3

      - name: pull image
        run: docker pull ${env:IMAGE}

      - name: print env
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src ${env:IMAGE} pwsh print-env.ps1

      - name: build
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src ${env:IMAGE} pwsh build.ps1

  vs-2022-17-3:
    runs-on: windows-2022
    env:
      IMAGE: ghcr.io/visualon/builder:2.5.71@sha256:df2605ff22ed0d4600e0b6d8894222923fa9d8ea7f6234eeeaae4d81fb955f3c

    steps:
      - uses: actions/checkout@v3

      - name: pull image
        run: docker pull ${env:IMAGE}

      - name: print env
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src ${env:IMAGE} pwsh print-env.ps1

      - name: build
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src ${env:IMAGE} pwsh build.ps1
