name: build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_NOLOGO: true
  ProjectLoadStyle: All
  IMAGE: ghcr.io/visualon/builder:3.0.2@sha256:a327b6b9fb832e39860ee316b5326cad62f46c648705d7590996d1ff0f2f129a

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: print env
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src $IMAGE pwsh print-env.ps1


      - name: build
        run: docker run --rm -t -v ${PWD}:c:\src -w c:\src $IMAGE msbuild Sample